### ISSUE TITLE
Authentication problem out of the box

### ISSUE THREAD

**Issue by dpanzer** [OfficeDev/O365-iOS-Profile#1]
Hi,

I've followed all the instructions to the T, but unfortunately I consistently get the following error when I try to log in within the app (I'm using an outlook.com account if that makes a difference):

```
2015-08-11 12:36:08.577 O365-iOS-Connect[77059:3506976] -[ADAuthenticationBroker webAuthenticationDidCompleteWithURL:][379][main] 
2015-08-11 12:36:09.265 O365-iOS-Connect[77059:3507075] ADALiOS [2015-08-11 16:36:09 - 6EAF6AAA-0528-4F38-8043-3F9C0437B768] ERROR: Error raised: 15. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:invalid_grant Details:AADSTS65001: No permission to access user information is configured for 'ad278137-XXXX-XXXX-XXXX-746574bb1089' application, or it is expired or revoked.
Trace ID: 05308aa0-1c42-4e9e-983c-ba2465be519a
Correlation ID: 6eaf6aaa-0528-4f38-8043-3f9c0437b768
Timestamp: 2015-08-11 16:36:07Z. ErrorCode: 15.
2015-08-11 12:36:09.266 O365-iOS-Connect[77059:3506976] Error in the authentication
```

I've tried every conceivable configuration of permissions on the Azure AD side - I've made sure that my app has the "Enable sign-on and read users' profiles" permission from "Windows Azure Active Directory" and I've literally enabled every single permission from "Office 365 unified API (preview)".

FWIW, I'm on a free trial O365 dev account / Azure subscription. I have also been running into the exact same authentication issue when trying to log in to the the other iOS samples (such as the repo O365-iOS-Connect) that use Office 365 Exchange Online rather than the unified preview.

Any help would be greatly appreciated.

**Comment by bmitchell287** [comment]
Hi dpanzer, could you try logging into this app, or the iOS Connect sample, using your O365 dev account credentials? Unfortunately these samples do not support authentication through accounts such as outlook.com.

**Comment by dpanzer** [comment]
@bmitchell287 Yep that worked. I don't know too much about the MSFT ecosystem (aren't outlook.com email accounts the most basic MSFT free email accounts, used by millions and millions of people?), but I assume that my app will need to authenticate these accounts. Is there something particular to these sample apps that prevents them from doing so?

**Comment by bmitchell287** [comment]
@dpanzer - The good news is ability to authenticate with accounts like outlook.com has just arrived. In fact this content was just posted on MSDN for the new auth model:

https://msdn.microsoft.com/en-us/office/office365/howto/authenticate-Office-365-APIs-using-v2 
https://msdn.microsoft.com/en-us/office/office365/howto/authentication-v2-whats-new 

For specifics please check them out. At this time we're trying to get samples ready to demonstrate this auth workflow for iOS. We'll post as soon as they're ready.

Thanks.

**Comment by dpanzer** [comment]
@bmitchell287 Sounds good thanks - in the meantime I just wrote the OAuth calls myself and am now successfully authenticating Microsoft accounts in my app. It wasn't super easy, though, I started following this guide: https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-protocols/#oauth2-authorization-code-flow

The one caveat there was that the /token POST request in that guide specifies a content-type of application/json and a json payload, but this was failing and instead I had to use a content-type of application/x-www-form-urlencoded and a standard key/value pair payload.

I'm guessing ADALiOS will be updated soon to streamline this?

**Comment by bmitchell287** [comment]
Glad you got it working on your end, and appreciate you running these iOS samples. For your ADALiOS follow up question (timeline), try fielding it to the Azure repo: https://github.com/AzureAD/azure-activedirectory-library-for-objc.  Best place to follow up on any Azure related issues/questions.
